name: dadayu_warehouse
version: '1.0.0'
config-version: 2

profile: dadayu

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
docs-paths: ["docs"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dadayu_warehouse:
    01_staging:
      +materialized: view
    02_intermediate:
      +materialized: view
    03_marts:
      +materialized: table

seeds:
  dadayu_warehouse:
    gics_hierarchy:
      +column_types:
        sector_id: text
        industry_group_id: text
        industry_id: text
        sub_industry_id: text
    equity_universe_extra:
      +column_types:
        ticker: text
        market: text
        name: text
        sector: text
        industry: text
    index_universe:
      +column_types:
        index_id: text
        ticker: text
        market: text
        name: text
        region: text
        benchmark_type: text
    macro_universe:
      +column_types:
        macro_id: text
        ticker: text
        market: text
        name: text
        instrument_type: text
        regime_dimension: text
    seed_index_membership_de:
      +column_types:
        ticker: text
        market: text
        index_name: text
        valid_from: date
        valid_to: date
    seed_index_membership_us:
      +column_types:
        ticker: text
        market: text
        index_name: text
        valid_from: date
        valid_to: date
    seed_index_name_ticker_map:
      +column_types:
        company_name: text
        ticker: text

snapshots:
  dadayu_warehouse:
    +target_schema: dadayu
