FROM python:3.12-slim
RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/app/dbt
COPY warehouse/requirements-dbt.txt .
RUN pip install --no-cache-dir -r requirements-dbt.txt
VOLUME ["/usr/app/dbt", "/root/.dbt"]
ENTRYPOINT ["dbt"]
CMD ["--help"]
